<form method="post" class="form-mailtemplate">
	<?php echo $this->h1(); ?>
	<div class="card card-tabs" id="page-edit-form">
		<div class="card-title">
			<ul class="tabs"><li data-tab="tab-main">{{lang:Main}}</li><li data-tab="tab-content">{{lang:Message content}}</li></ul>
		</div>
		<div class="card-body">
			<div class="tab" id="tab-main"><?php echo $this->form->report(), $this->form->render('name', 'type', 'parent_id'); ?></div>
			<div class="tab fields-justify" id="tab-content"><?php echo $this->form->render('subject', 'body'); ?></div>
		</div>
	</div>
	<?php $this->renderTemplate('default', 'form-buttons'); ?>
</form>
<script type="text/javascript">
$(document).ready(function(){
	$('#page-edit-form').tabs();
});
</script>