<div class="head"><span class="method">GET</span><span class="url">/categories/</span> — Список категорий проектов.</div>
<h3>Общие параметры</h3>
<ul>
	<li><span class="l">Параметры списка</span></li>
	<li><span class="l">Сайт</span></li>
	<li><span class="l">Страна</span></li>
</ul>
<div class="result">
	<h3>Ответ <span>[массив]</span></h3>
	<div class="params">
		<table>
			<tr>
				<th>id</th>
				<td>Идентификатор<div class="param-opts"><b>целочисленный</b></div></td>
			</tr>
			<tr>
				<th>name</th>
				<td>Наименование</td>
			</tr>
			<tr>
				<th>text</th>
				<td>HTML описание</td>
			</tr>
			<tr>
				<th>image</th>
				<td>Изображение<div class="param-opts"><b>картинка</b></div></td>
			</tr>
			<tr>
				<th>popular</th>
				<td>Популярные<div class="param-opts"><b>булево</b></div></td>
			</tr>
			<tr>
				<th>icon</th>
				<td>Изображение<div class="param-opts"><b>картинка</b></div></td>
			</tr>
		</table>
	</div>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


