<div class="head"><span class="method">GET</span><span class="url">/countries/</span> — Список стран.</div>
<h3>Общие параметры</h3>
<ul>
	<li><span class="l">Параметры списка</span></li>
</ul>
<div class="result">
	<h3>Ответ <span>[массив]</span></h3>
	<div class="params">
		<table>
			<tr>
				<th>id</th>
				<td>Идентификатор страны<div class="param-opts"><b>целочисленный</b></div></td>
			</tr>
			<tr>
				<th>name</th>
				<td>Наименование</td>
			</tr>
			<tr>
				<th>default</th>
				<td>Страна по умолчанию<div class="param-opts"><b>булево</b></div></td>
			</tr>
			<tr>
				<th>language</th>
				<td>Язык страны по умолчанию<div class="param-opts"><b>ru, en, uz</b></div></td>
			</tr>
			<tr>
				<th>flag</th>
				<td>Код флага страны<div class="param-opts"><b>ru, en, uz</b></div></td>
			</tr>
			<tr>
				<th>phone_code</th>
				<td>Телефонный код страны</td>
			</tr>
			<tr>
				<th>icon</th>
				<td>Адрес иконки флага</td>
			</tr>
		</table>
	</div>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


