<div class="head"><span class="method">GET</span><span class="url">/experiences/</span> — Список опыта работы для мастеров.</div>
<h3>Общие параметры</h3>
<ul>
	<li><span class="l">Параметры списка</span></li>
</ul>
<div class="result">
	<h3>Ответ <span>[массив]</span></h3>
	<div class="params">
		<table>
			<tr>
				<th>id</th>
				<td>Идентификатор<div class="param-opts"><b>целочисленный</b></div></td>
			</tr>
			<tr>
				<th>name</th>
				<td>Наименование</td>
			</tr>
		</table>
	</div>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


