<div class="head"><span class="method">GET</span><span class="url">/profile/masters/</span> — Список избранных мастеров пользователя.</div>
<h3>Общие параметры</h3>
<ul>
	<li><span class="l">Авторизация</span></li>
</ul>
<div class="result">
	<h3>Ответ <span>[массив]</span></h3>
	<p>Поля элементов см. <a href="#profile">Профиль</a> (Для мастера).</p>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


