<div class="head"><span class="method">POST</span><span class="url">/master/<b>ID</b>/callback/</span> — Добавить проект в избранное.</div>
<h3>Общие параметры</h3>
<div class="params">
	<h3>Параметры</h3>
	<table>
		<tr>
			<th>Авторизация</th>
			<td></td>
		</tr>
		<tr>
			<th>ID</th>
			<td>Идентификатор мастера.<div class="param-opts"><b>обязательный</b></div></td>
		</tr>
		<tr>
			<th>phone</th>
			<td>Номер телефона для обратного звонка.<div class="param-opts"><b>обязательный</b></div></td>
		</tr>
		<tr>
			<th>time</th>
			<td>Удобное время.<div class="param-opts"><b>обязательный</b></div></td>
		</tr>
	</table>
</div>
<div class="result">
	<h3>Ответ <span>булево</span></h3>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


