<div class="head"><span class="method">GET</span><span class="url">/price/category/<b>ID</b>/</span> — Страница цен.</div>
<h3>Общие параметры</h3>
<div class="params">
	<h3>Параметры</h3>
	<table>
		<tr>
			<th>ID</th>
			<td>Идентификатор категории.<div class="param-opts"><b>обязательный</b></div></td>
		</tr>
	</table>
</div>
<div class="result">
	<h3>Ответ <span>{объект}</span></h3>
	<div class="params">
		<table>
			<tr>
				<th>id</th>
				<td>Идентификатор страницы<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>country_id</th>
				<td>Идентификатор страны<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>category_id</th>
				<td>Идентификатор категории<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>title</th>
				<td>Заголовок страницы</td>
			</tr>
			<tr>
				<th>title_chart</th>
				<td>Заголовок графика</td>
			</tr>
			<tr>
				<th>title_service</th>
				<td>Заголовок услуг</td>
			</tr>
			<tr>
				<th>title_text</th>
				<td>Заголовок текста</td>
			</tr>
			<tr>
				<th>text</th>
				<td>Текст</td>
			</tr>
		</table>
		<h3>prices <span>{объект}</span> Цены</h3>
		<table>
			<tr>
				<th>id</th>
				<td>Идентификатор<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>country_id</th>
				<td>Идентификатор страны<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>category_id</th>
				<td>Идентификатор категории<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>price</th>
				<td>Стоимость</td>
			</tr>
			<tr>
				<th>units</th>
				<td>Единицы измерения</td>
			</tr>
		</table>
		<h3>services <span>{объект}</span> Услуги<h3>
		<table>
			<tr>
				<th>id</th>
				<td>Идентификатор<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>country_id</th>
				<td>Идентификатор страны<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>category_id</th>
				<td>Идентификатор категории<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>price</th>
				<td>Стоимость</td>
			</tr>
			<tr>
				<th>units</th>
				<td>Единицы измерения</td>
			</tr>
		</table>
	</div>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


