<div class="head"><span class="method">GET</span><span class="url">/project/<b>ID</b>/</span> — Данные проекта.</div>
<div class="params">
	<h3>Параметры</h3>
	<table>
		<tr>
			<th>ID</th>
			<td>Идентификатор проекта.<div class="param-opts"><b>обязательный</b></div></td>
		</tr>
	</table>
</div>
<div class="result">
	<h3>Ответ <span>{объект}</span></h3>
	<div class="params">
		<table>
			<tr>
				<th>id</th>
				<td>Идентификатор<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>type</th>
				<td>Тип проекта<div class="param-opts"><a href="#enums">Перечисления.Тип проекта</a></div></td>
			</tr>
			<tr>
				<th>country_id</th>
				<td>Идентификатор страны<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>category_id</th>
				<td>Идентификатор категории<div class="param-opts">целочисленный</div></td>
			</tr>
			<tr>
				<th>category_name</th>
				<td>Наименование катогории.</td>
			</tr>
			<tr>
				<th>name</th>
				<td>Наименование</td>
			</tr>
			<tr>
				<th>images</th>
				<td>Основное изображение<div class="param-opts">картинка</div></td>
			</tr>
			<tr>
				<th>master_id</th>
				<td>Идентификатор мастера.</td>
			</tr>
			<tr>
				<th>master_presentation</th>
				<td>Полное имя мастера.</td>
			</tr>
			<tr>
				<th>master_phone</th>
				<td>Телефон мастера.</td>
			</tr>
			<tr>
				<th>master_about</th>
				<td>Описание "О себе" мастера.</td>
			</tr>
			<tr>
				<th>text</th>
				<td>Описание проекта.</td>
			</tr>
			<tr>
				<th>master_badges</th>
				<td>Количество бейджиков мастера.</td>
			</tr>
			<tr>
				<th>master_rating</th>
				<td>Рейтинг мастера.</td>
			</tr>
			<tr>
				<th>master_avatar</th>
				<td>Изображение мастера.<div class="param-opts">картинка</div></td>
			</tr>
			<tr>
				<th>url</th>
				<td>Адрес проекта в интернет.</td>
			</tr>
			<tr>
				<th>discount</th>
				<td>Скидка.</td>
			</tr>
			<tr>
				<th>discount_terms</th>
				<td>Описание скидки.</td>
			</tr>
			<tr>
				<th>delivery</th>
				<td>Описание доставки.</td>
			</tr>
		</table>
	</div>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


