<div class="head"><span class="method">POST</span><span class="url">/registration/confirm/<b>CODE</b>/</span> — Подтверждение регистрации.</div>
<div class="params">
	<h3>Параметры</h3>
	<table>
		<tr>
			<th>CODE</th>
			<td>Код авторизации, отправленный при регистрации.<div class="param-opts"><b>обязательный</b></div></td>
		</tr>
	</table>
</div>
<div class="result">
	<h3>Ответ <span>булево</span></h3>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<table>
		<tr>
			<th>User not found</th>
			<td>Не удалось найти пользователя с передаваемым кодом</td>
		</tr>
	</table>
</div>
