<div class="head"><span class="method">POST</span><span class="url">/user/order/</span> — Отправить заявку на поиск мастера.</div>
<h3>Общие параметры</h3>
<ul>
	<li><span class="l">Авторизация (не обязательный)</span></li>
</ul>
<div class="params">
	<h3>Параметры</h3>
	<table>
		<tr>
			<th>username</th>
			<td>
				Имя пользователя
				<div class="param-opts"><b>обязательный</b></div>
			</td>
		</tr>
		<tr>
			<th>phone</th>
			<td>Телефон</td>
		</tr>
		<tr>
			<th>service</th>
			<td>Тип услуги</td>
		</tr>
		<tr>
			<th>text</th>
			<td>Описание заявки</td>
		</tr>
		<tr>
			<th>address</th>
			<td>Адрес</td>
		</tr>
	</table>
</div>
<div class="result">
	<h3>Ответ <span>булево</span></h3>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


