<div class="head"><span class="method">POST</span><span class="url">/user/password/</span> — Формирует письмо с ссылкой для смены пароля пользователя.</div>
<div class="params">
	<h3>Параметры</h3>
	<table>
		<tr>
			<th>email</th>
			<td>Email пользователя для которого нужно изменить пароль, на этот адрес будет отправлено письмо с ссылкой для смены пароля.<div class="param-opts"><b>обязательный</b></div></td>
		</tr>
	</table>
</div>
<div class="result">
	<h3>Ответ <span>булево</span></h3>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


