<div class="head"><span class="method">POST</span><span class="url">/user/edit/</span> — Изменить данные авторизованного пользователя.</div>
<h3>Общие параметры</h3>
<ul>
	<li><span class="l">Авторизация</span></li>
</ul>
<div class="params">
	<h3>Параметры</h3>
	<table>
		<tr>
			<th>login</th>
			<td>
				Логин пользователя, телефон или email.
				<div class="param-opts"><b>обязательный</b></div>
			</td>
		</tr>
		<tr>
			<th>password</th>
			<td>
				Пароль пользователя.
				<div class="param-opts"><b>обязательный</b></div>
			</td>
		</tr>
	</table>
</div>
<div class="result">
	<h3>Ответ <span>булево</span></h3>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


