<div class="head"><span class="method">GET</span><span class="url">/vendor/<b>ID</b>/remove/</span> — Удалить мастера из избранного.</div>
<h3>Общие параметры</h3>
<ul>
	<li><span class="l">Авторизация</span></li>
</ul>
<div class="params">
	<h3>Параметры</h3>
	<table>
		<tr>
			<th>ID</th>
			<td>Идентификатор мастера.<div class="param-opts">целочисленный, <b>обязательный</b></div></td>
		</tr>
	</table>
</div>
<div class="result">
	<h3>Ответ <span>булево</span></h3>
</div>
<div class="erors">
	<h3>Ошибки</h3>
	<p>В ходе выполнения могут произойти общие ошибки.</p>
</div>


